### PR TITLE
minisatip: remove request

### PR DESCRIPTION
**Pull request by walterav1984**
This package is already part of OpenWrt packages feed [1]
A newer version (not newest) is already included in OpenWrt 21.02 [2]

[1]https://github.com/openwrt/packages/commit/380c6fa780e81d0e5568c632bccc4cdd39e7d81d
[2]https://github.com/openwrt/packages/blob/openwrt-21.02/multimedia/minisatip/Makefile

Note:It can be removed if the OpenWrt version does include libdvben50221?

### CODE REVIEW

**Comment by BKPepe** [comment]
> Note:It can be removed if the OpenWrt version does include libdvben50221?

I will send shortly libdvben50221 to OpenWrt packages feed for review and then this can be removed.

**Comment by walterav1984** [comment]
> I will send shortly libdvben50221 to OpenWrt packages feed for review and then this can be removed.

Does this mean that OpenWrt get its own "dvb-apps" package in multimedia feed instead of tmn505?

Although minisatip itself can indeed also support common interfaces with CAMs with this libdvben50221, TvHeadend might benefit as well if compiled with [dvb-apps(libdvben50221)](https://tvheadend.org/boards/13/topics/22272) support(when not using minisatip). 

Can test "Technotrend dvb-s2 budget-ci common interface" with several CAMs to see if they get detected. It worked in the past on ubuntu 16.04 with tvheadend. CAMs show up as a extrabox under the dvb-tuner in the adapters section if Tvheadend was compiled with correct support, otherwise only the tuner was listed under adapters.

Funny contradiction though is that currently minisatip is trying to [get rid of dvb-apps](https://github.com/catalinii/minisatip/pull/961) dependency...

**Comment by zhengjun131461** [comment]
X86编译错误
make[7]: *** [scripts/Makefile.build:288: /home/zhengjun/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/linux-x86_64/v4l-dvb-tbsdtv-2021-02-02-ad3104e0/v4l/msp3400-driver.o] Error 1
make[6]: *** [Makefile:1868: /home/zhengjun/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/linux-x86_64/v4l-dvb-tbsdtv-2021-02-02-ad3104e0/v4l] Error 2
make[6]: Leaving directory '/home/zhengjun/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.48'
make[5]: *** [Makefile:53: default] Error 2
make[5]: Leaving directory '/home/zhengjun/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/linux-x86_64/v4l-dvb-tbsdtv-2021-02-02-ad3104e0/v4l'
make[4]: *** [Makefile:26: all] Error 2
make[4]: Leaving directory '/home/zhengjun/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/linux-x86_64/v4l-dvb-tbsdtv-2021-02-02-ad3104e0'
make[3]: *** [Makefile:87: /home/zhengjun/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/linux-x86_64/v4l-dvb-tbsdtv-2021-02-02-ad3104e0/.built] Error 2
make[3]: Leaving directory '/home/zhengjun/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64/package/openwrt-dvb/v4l-dvb'
time: package/openwrt-dvb/v4l-dvb/compile#3.72#1.07#12.68
    ERROR: package/openwrt-dvb/v4l-dvb failed to build.
make[2]: *** [package/Makefile:116: package/openwrt-dvb/v4l-dvb/compile] Error 1
make[2]: Leaving directory '/home/zhengjun/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64'
make[1]: *** [package/Makefile:110: /home/zhengjun/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/zhengjun/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64'
make: *** [/home/zhengjun/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64/include/toplevel.mk:223：world] 错误 2

**Comment by lars18th** [comment]
Hi @walterav1984 and @BKPepe ,

I would please suggest you if it's possible to also send a PR to the OpenWRT packages from the main stream of the SATPI package. This project (`satpi`) can be used without DVB drivers using the vitual tuners inputs: FILE, STREAMER and CHILDPIPE.

**Pull request merged**
